<?php

use Illuminate\Database\Seeder;

class VehiclesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vehicles')->delete();
        
        \DB::table('vehicles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'propietario' => 'Tren',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'propietario' => 'Bus',
                'modelo' => 0,
                'precio' => 0,
                'x' => 0.0,
                'y' => 0.0,
                'z' => 0.0,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'propietario' => 'Gobierno',
                'modelo' => 596,
                'precio' => 0,
                'x' => 1604.21,
                'y' => -1607.02,
                'z' => 13.1746,
                'a' => 87.4326,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'propietario' => 'Gobierno',
                'modelo' => 596,
                'precio' => 0,
                'x' => 1603.85,
                'y' => -1617.49,
                'z' => 13.129,
                'a' => 85.9502,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'propietario' => 'Gobierno',
                'modelo' => 596,
                'precio' => 0,
                'x' => 1603.49,
                'y' => -1623.18,
                'z' => 13.129,
                'a' => 87.0255,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'propietario' => 'Gobierno',
                'modelo' => 596,
                'precio' => 0,
                'x' => 1603.43,
                'y' => -1628.43,
                'z' => 13.2271,
                'a' => 87.0,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            22 => 
            array (
                'id' => 23,
                'propietario' => 'Gobierno',
                'modelo' => 596,
                'precio' => 0,
                'x' => 1570.0,
                'y' => -1606.25,
                'z' => 13.028,
                'a' => 179.513,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            23 => 
            array (
                'id' => 24,
                'propietario' => 'Gobierno',
                'modelo' => 596,
                'precio' => 0,
                'x' => 1582.3,
                'y' => -1606.19,
                'z' => 13.028,
                'a' => 179.513,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            24 => 
            array (
                'id' => 25,
                'propietario' => 'Gobierno',
                'modelo' => 596,
                'precio' => 0,
                'x' => 1563.95,
                'y' => -1606.42,
                'z' => 13.028,
                'a' => 179.513,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'propietario' => 'Gobierno',
                'modelo' => 596,
                'precio' => 0,
                'x' => 1576.23,
                'y' => -1606.29,
                'z' => 13.028,
                'a' => 179.513,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            26 => 
            array (
                'id' => 27,
                'propietario' => 'Gobierno',
                'modelo' => 596,
                'precio' => 0,
                'x' => 1603.99,
                'y' => -1612.1,
                'z' => 13.1746,
                'a' => 87.4326,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            27 => 
            array (
                'id' => 28,
                'propietario' => 'Gobierno',
                'modelo' => 596,
                'precio' => 0,
                'x' => 1535.83,
                'y' => -1668.24,
                'z' => 13.0436,
                'a' => 359.555,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'propietario' => 'Gobierno',
                'modelo' => 596,
                'precio' => 0,
                'x' => 1535.75,
                'y' => -1678.29,
                'z' => 13.0437,
                'a' => 359.551,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            29 => 
            array (
                'id' => 30,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => 1616.56,
                'y' => 1830.91,
                'z' => 10.9195,
                'a' => 178.945,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            30 => 
            array (
                'id' => 31,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => 1178.3,
                'y' => -1338.5,
                'z' => 14.2,
                'a' => 270.0,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            31 => 
            array (
                'id' => 32,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => 1179.65,
                'y' => -1308.65,
                'z' => 13.897,
                'a' => 268.682,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            32 => 
            array (
                'id' => 33,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => 1192.11,
                'y' => -1347.71,
                'z' => 13.4992,
                'a' => 180.55,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            33 => 
            array (
                'id' => 34,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => 1209.44,
                'y' => -1348.43,
                'z' => 13.5497,
                'a' => 0.476262,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            34 => 
            array (
                'id' => 35,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => 1209.24,
                'y' => -1318.81,
                'z' => 13.548,
                'a' => 0.4484,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            35 => 
            array (
                'id' => 36,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => 2032.72,
                'y' => -1447.62,
                'z' => 17.2888,
                'a' => 88.6918,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            36 => 
            array (
                'id' => 37,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => 2000.81,
                'y' => -1409.93,
                'z' => 17.1158,
                'a' => 179.339,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => 1601.15,
                'y' => 1849.37,
                'z' => 10.9196,
                'a' => 178.724,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            38 => 
            array (
                'id' => 39,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => 1611.12,
                'y' => 1839.96,
                'z' => 10.9192,
                'a' => 359.882,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            39 => 
            array (
                'id' => 40,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => 1594.38,
                'y' => 1839.87,
                'z' => 10.9694,
                'a' => 359.98,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            40 => 
            array (
                'id' => 41,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => -2693.72,
                'y' => 624.903,
                'z' => 14.5523,
                'a' => 124.597,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            41 => 
            array (
                'id' => 42,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => -2701.97,
                'y' => 611.621,
                'z' => 14.5533,
                'a' => 163.926,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            42 => 
            array (
                'id' => 43,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => -2698.83,
                'y' => 592.078,
                'z' => 14.5525,
                'a' => 211.119,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            43 => 
            array (
                'id' => 44,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => -2676.72,
                'y' => 630.13,
                'z' => 14.6021,
                'a' => 87.9904,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            44 => 
            array (
                'id' => 45,
                'propietario' => 'Gobierno',
                'modelo' => 416,
                'precio' => 0,
                'x' => -2648.34,
                'y' => 583.903,
                'z' => 14.6026,
                'a' => 270.434,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            45 => 
            array (
                'id' => 46,
                'propietario' => 'Gobierno',
                'modelo' => 532,
                'precio' => 0,
                'x' => -373.803,
                'y' => -1534.98,
                'z' => 22.4199,
                'a' => 287.827,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            46 => 
            array (
                'id' => 47,
                'propietario' => 'Gobierno',
                'modelo' => 532,
                'precio' => 0,
                'x' => -372.074,
                'y' => -1546.07,
                'z' => 22.3238,
                'a' => 277.034,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            47 => 
            array (
                'id' => 48,
                'propietario' => 'Gobierno',
                'modelo' => 532,
                'precio' => 0,
                'x' => -387.014,
                'y' => -1496.41,
                'z' => 25.9259,
                'a' => 275.834,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            48 => 
            array (
                'id' => 49,
                'propietario' => 'Gobierno',
                'modelo' => 532,
                'precio' => 0,
                'x' => -383.597,
                'y' => -1508.68,
                'z' => 24.7948,
                'a' => 292.234,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            49 => 
            array (
                'id' => 50,
                'propietario' => 'Gobierno',
                'modelo' => 532,
                'precio' => 0,
                'x' => -378.054,
                'y' => -1522.55,
                'z' => 23.2702,
                'a' => 291.41,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            50 => 
            array (
                'id' => 51,
                'propietario' => 'Gobierno',
                'modelo' => 598,
                'precio' => 0,
                'x' => 2277.83,
                'y' => 2442.71,
                'z' => 10.5653,
                'a' => 0.539601,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            51 => 
            array (
                'id' => 52,
                'propietario' => 'Gobierno',
                'modelo' => 598,
                'precio' => 0,
                'x' => 2269.05,
                'y' => 2442.94,
                'z' => 10.5658,
                'a' => 0.734632,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            52 => 
            array (
                'id' => 53,
                'propietario' => 'Gobierno',
                'modelo' => 598,
                'precio' => 0,
                'x' => 2256.36,
                'y' => 2442.86,
                'z' => 10.5666,
                'a' => 359.091,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            53 => 
            array (
                'id' => 54,
                'propietario' => 'Gobierno',
                'modelo' => 598,
                'precio' => 0,
                'x' => 2260.61,
                'y' => 2478.26,
                'z' => 10.5673,
                'a' => 177.463,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            54 => 
            array (
                'id' => 55,
                'propietario' => 'Gobierno',
                'modelo' => 598,
                'precio' => 0,
                'x' => 2273.19,
                'y' => 2478.21,
                'z' => 10.565,
                'a' => 180.937,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            55 => 
            array (
                'id' => 56,
                'propietario' => 'Gobierno',
                'modelo' => 598,
                'precio' => 0,
                'x' => 2282.35,
                'y' => 2478.35,
                'z' => 10.5645,
                'a' => 179.952,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            56 => 
            array (
                'id' => 57,
                'propietario' => 'Gobierno',
                'modelo' => 598,
                'precio' => 0,
                'x' => 2273.54,
                'y' => 2460.66,
                'z' => 10.5684,
                'a' => 181.299,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            57 => 
            array (
                'id' => 58,
                'propietario' => 'Gobierno',
                'modelo' => 597,
                'precio' => 0,
                'x' => -1634.72,
                'y' => 650.963,
                'z' => 6.95528,
                'a' => 2.03608,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 1,
                'trabajo' => 0,
            ),
            58 => 
            array (
                'id' => 59,
                'propietario' => 'Gobierno',
                'modelo' => 597,
                'precio' => 0,
                'x' => -1628.61,
                'y' => 651.29,
                'z' => 6.96142,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 1,
                'trabajo' => 0,
            ),
            59 => 
            array (
                'id' => 60,
                'propietario' => 'Gobierno',
                'modelo' => 597,
                'precio' => 0,
                'x' => -1622.04,
                'y' => 651.358,
                'z' => 6.97341,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 1,
                'trabajo' => 0,
            ),
            60 => 
            array (
                'id' => 61,
                'propietario' => 'Gobierno',
                'modelo' => 597,
                'precio' => 0,
                'x' => -1615.67,
                'y' => 651.832,
                'z' => 6.91138,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 1,
                'trabajo' => 0,
            ),
            61 => 
            array (
                'id' => 62,
                'propietario' => 'Gobierno',
                'modelo' => 597,
                'precio' => 0,
                'x' => -1609.34,
                'y' => 650.495,
                'z' => 6.97994,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 1,
                'trabajo' => 0,
            ),
            62 => 
            array (
                'id' => 63,
                'propietario' => 'Gobierno',
                'modelo' => 597,
                'precio' => 0,
                'x' => -1604.17,
                'y' => 651.536,
                'z' => 6.98966,
                'a' => 0.0,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 1,
                'trabajo' => 0,
            ),
            63 => 
            array (
                'id' => 64,
                'propietario' => 'Gobierno',
                'modelo' => 420,
                'precio' => 0,
                'x' => 1803.73,
                'y' => -1904.79,
                'z' => 13.1791,
                'a' => 91.2167,
                'color1' => '6',
                'color2' => '6',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            64 => 
            array (
                'id' => 65,
                'propietario' => 'Gobierno',
                'modelo' => 420,
                'precio' => 0,
                'x' => 1804.0,
                'y' => -1912.51,
                'z' => 13.176,
                'a' => 92.5541,
                'color1' => '6',
                'color2' => '6',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            65 => 
            array (
                'id' => 66,
                'propietario' => 'Gobierno',
                'modelo' => 420,
                'precio' => 0,
                'x' => 1804.4,
                'y' => -1921.97,
                'z' => 13.1708,
                'a' => 94.8712,
                'color1' => '6',
                'color2' => '6',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            66 => 
            array (
                'id' => 67,
                'propietario' => 'Gobierno',
                'modelo' => 420,
                'precio' => 0,
                'x' => 1794.89,
                'y' => -1932.77,
                'z' => 13.1659,
                'a' => 0.0,
                'color1' => '6',
                'color2' => '6',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            67 => 
            array (
                'id' => 68,
                'propietario' => 'Gobierno',
                'modelo' => 420,
                'precio' => 0,
                'x' => 1787.06,
                'y' => -1932.7,
                'z' => 13.1649,
                'a' => 1.4882,
                'color1' => '6',
                'color2' => '6',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            68 => 
            array (
                'id' => 69,
                'propietario' => 'Gobierno',
                'modelo' => 420,
                'precio' => 0,
                'x' => 1775.58,
                'y' => -1913.91,
                'z' => 13.1637,
                'a' => 180.1,
                'color1' => '6',
                'color2' => '6',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            69 => 
            array (
                'id' => 70,
                'propietario' => 'Gobierno',
                'modelo' => 509,
                'precio' => 0,
                'x' => 1703.04,
                'y' => -1876.09,
                'z' => 13.0807,
                'a' => 270.348,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            70 => 
            array (
                'id' => 71,
                'propietario' => 'Gobierno',
                'modelo' => 509,
                'precio' => 0,
                'x' => 1703.31,
                'y' => -1879.1,
                'z' => 13.0807,
                'a' => 269.464,
                'color1' => '2',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            71 => 
            array (
                'id' => 72,
                'propietario' => 'Gobierno',
                'modelo' => 509,
                'precio' => 0,
                'x' => 1703.09,
                'y' => -1881.77,
                'z' => 13.0807,
                'a' => 269.007,
                'color1' => '3',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            72 => 
            array (
                'id' => 73,
                'propietario' => 'Gobierno',
                'modelo' => 509,
                'precio' => 0,
                'x' => 1703.16,
                'y' => -1884.97,
                'z' => 13.0807,
                'a' => 271.961,
                'color1' => '4',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            73 => 
            array (
                'id' => 74,
                'propietario' => 'Gobierno',
                'modelo' => 509,
                'precio' => 0,
                'x' => 1710.91,
                'y' => -1875.39,
                'z' => 13.0807,
                'a' => 178.176,
                'color1' => '5',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            74 => 
            array (
                'id' => 75,
                'propietario' => 'Gobierno',
                'modelo' => 509,
                'precio' => 0,
                'x' => 1718.93,
                'y' => -1875.06,
                'z' => 13.0807,
                'a' => 176.381,
                'color1' => '6',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            75 => 
            array (
                'id' => 76,
                'propietario' => 'Gobierno',
                'modelo' => 509,
                'precio' => 0,
                'x' => 1727.03,
                'y' => -1875.78,
                'z' => 13.0807,
                'a' => 89.5347,
                'color1' => '7',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            76 => 
            array (
                'id' => 77,
                'propietario' => 'Gobierno',
                'modelo' => 509,
                'precio' => 0,
                'x' => 1727.05,
                'y' => -1878.48,
                'z' => 13.0807,
                'a' => 88.3724,
                'color1' => '8',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            77 => 
            array (
                'id' => 78,
                'propietario' => 'Gobierno',
                'modelo' => 509,
                'precio' => 0,
                'x' => 1727.32,
                'y' => -1881.84,
                'z' => 13.0807,
                'a' => 87.3723,
                'color1' => '9',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            78 => 
            array (
                'id' => 79,
                'propietario' => 'Gobierno',
                'modelo' => 509,
                'precio' => 0,
                'x' => 1726.99,
                'y' => -1884.81,
                'z' => 13.0807,
                'a' => 90.4685,
                'color1' => '10',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            79 => 
            array (
                'id' => 80,
                'propietario' => 'Gobierno',
                'modelo' => 456,
                'precio' => 0,
                'x' => -1610.98,
                'y' => 92.0841,
                'z' => 3.76232,
                'a' => 224.869,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            80 => 
            array (
                'id' => 81,
                'propietario' => 'Gobierno',
                'modelo' => 456,
                'precio' => 0,
                'x' => -1596.6,
                'y' => 106.977,
                'z' => 3.75996,
                'a' => 227.321,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            81 => 
            array (
                'id' => 82,
                'propietario' => 'Gobierno',
                'modelo' => 456,
                'precio' => 0,
                'x' => -1569.15,
                'y' => 134.842,
                'z' => 3.76286,
                'a' => 222.82,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            82 => 
            array (
                'id' => 83,
                'propietario' => 'Gobierno',
                'modelo' => 456,
                'precio' => 0,
                'x' => -1589.2,
                'y' => 114.527,
                'z' => 3.75991,
                'a' => 225.743,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            83 => 
            array (
                'id' => 84,
                'propietario' => 'Gobierno',
                'modelo' => 456,
                'precio' => 0,
                'x' => -1575.13,
                'y' => 128.513,
                'z' => 3.76237,
                'a' => 224.698,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            84 => 
            array (
                'id' => 85,
                'propietario' => 'Gobierno',
                'modelo' => 456,
                'precio' => 0,
                'x' => -1756.0,
                'y' => -168.843,
                'z' => 3.7296,
                'a' => 23.5515,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            85 => 
            array (
                'id' => 86,
                'propietario' => 'Gobierno',
                'modelo' => 456,
                'precio' => 0,
                'x' => -1624.5,
                'y' => 78.0176,
                'z' => 3.72969,
                'a' => 226.847,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            86 => 
            array (
                'id' => 87,
                'propietario' => 'Gobierno',
                'modelo' => 456,
                'precio' => 0,
                'x' => -1738.25,
                'y' => -160.199,
                'z' => 3.72397,
                'a' => 27.7106,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            87 => 
            array (
                'id' => 88,
                'propietario' => 'Gobierno',
                'modelo' => 456,
                'precio' => 0,
                'x' => -1722.04,
                'y' => -150.78,
                'z' => 3.72947,
                'a' => 27.9671,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            88 => 
            array (
                'id' => 89,
                'propietario' => 'Gobierno',
                'modelo' => 498,
                'precio' => 0,
                'x' => -1604.97,
                'y' => 100.193,
                'z' => 3.52903,
                'a' => 223.577,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            89 => 
            array (
                'id' => 90,
                'propietario' => 'Gobierno',
                'modelo' => 498,
                'precio' => 0,
                'x' => -1747.31,
                'y' => -167.437,
                'z' => 3.62394,
                'a' => 26.2029,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            90 => 
            array (
                'id' => 91,
                'propietario' => 'Gobierno',
                'modelo' => 498,
                'precio' => 0,
                'x' => -1619.41,
                'y' => 85.3535,
                'z' => 3.64475,
                'a' => 227.137,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            91 => 
            array (
                'id' => 92,
                'propietario' => 'Gobierno',
                'modelo' => 498,
                'precio' => 0,
                'x' => -1583.27,
                'y' => 122.162,
                'z' => 3.5391,
                'a' => 223.746,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            92 => 
            array (
                'id' => 93,
                'propietario' => 'Gobierno',
                'modelo' => 498,
                'precio' => 0,
                'x' => -1728.35,
                'y' => -157.114,
                'z' => 3.62526,
                'a' => 27.4225,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            93 => 
            array (
                'id' => 94,
                'propietario' => 'Gobierno',
                'modelo' => 609,
                'precio' => 0,
                'x' => -1657.92,
                'y' => 41.6746,
                'z' => 3.62129,
                'a' => 223.094,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            94 => 
            array (
                'id' => 95,
                'propietario' => 'Gobierno',
                'modelo' => 609,
                'precio' => 0,
                'x' => -1650.75,
                'y' => 48.5277,
                'z' => 3.62627,
                'a' => 224.525,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            95 => 
            array (
                'id' => 96,
                'propietario' => 'Gobierno',
                'modelo' => 609,
                'precio' => 0,
                'x' => -1636.34,
                'y' => 63.6219,
                'z' => 3.62438,
                'a' => 226.384,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            96 => 
            array (
                'id' => 97,
                'propietario' => 'Gobierno',
                'modelo' => 609,
                'precio' => 0,
                'x' => -1642.93,
                'y' => 56.4085,
                'z' => 3.62169,
                'a' => 224.717,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            97 => 
            array (
                'id' => 98,
                'propietario' => 'Gobierno',
                'modelo' => 609,
                'precio' => 0,
                'x' => -1616.34,
                'y' => 43.767,
                'z' => 3.62439,
                'a' => 45.3192,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            98 => 
            array (
                'id' => 99,
                'propietario' => 'Gobierno',
                'modelo' => 609,
                'precio' => 0,
                'x' => -1623.14,
                'y' => 36.8284,
                'z' => 3.62389,
                'a' => 44.374,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            99 => 
            array (
                'id' => 100,
                'propietario' => 'Gobierno',
                'modelo' => 609,
                'precio' => 0,
                'x' => -1631.32,
                'y' => 28.6976,
                'z' => 3.62297,
                'a' => 45.1211,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            100 => 
            array (
                'id' => 101,
                'propietario' => 'Gobierno',
                'modelo' => 609,
                'precio' => 0,
                'x' => -1638.38,
                'y' => 21.5687,
                'z' => 3.62106,
                'a' => 45.3911,
                'color1' => '0',
                'color2' => '0',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            101 => 
            array (
                'id' => 102,
                'propietario' => 'Gobierno',
                'modelo' => 523,
                'precio' => 0,
                'x' => 1570.59,
                'y' => -1709.75,
                'z' => 5.4615,
                'a' => 2.0359,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            102 => 
            array (
                'id' => 103,
                'propietario' => 'Gobierno',
                'modelo' => 523,
                'precio' => 0,
                'x' => 1574.34,
                'y' => -1709.23,
                'z' => 5.4581,
                'a' => 358.051,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            103 => 
            array (
                'id' => 104,
                'propietario' => 'Gobierno',
                'modelo' => 523,
                'precio' => 0,
                'x' => 1578.79,
                'y' => -1709.33,
                'z' => 5.4587,
                'a' => 2.4554,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            104 => 
            array (
                'id' => 105,
                'propietario' => 'Gobierno',
                'modelo' => 523,
                'precio' => 0,
                'x' => 1583.58,
                'y' => -1709.6,
                'z' => 5.4615,
                'a' => 0.1382,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            105 => 
            array (
                'id' => 106,
                'propietario' => 'Gobierno',
                'modelo' => 523,
                'precio' => 0,
                'x' => 1587.66,
                'y' => -1709.85,
                'z' => 5.4616,
                'a' => 358.432,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            106 => 
            array (
                'id' => 107,
                'propietario' => 'Gobierno',
                'modelo' => 601,
                'precio' => 0,
                'x' => 1530.55,
                'y' => -1646.76,
                'z' => 5.6494,
                'a' => 181.887,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            107 => 
            array (
                'id' => 108,
                'propietario' => 'Gobierno',
                'modelo' => 601,
                'precio' => 0,
                'x' => 1538.79,
                'y' => -1646.99,
                'z' => 5.6493,
                'a' => 181.301,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            108 => 
            array (
                'id' => 109,
                'propietario' => 'Gobierno',
                'modelo' => 528,
                'precio' => 0,
                'x' => 1544.64,
                'y' => -1612.51,
                'z' => 13.3795,
                'a' => 268.785,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            109 => 
            array (
                'id' => 110,
                'propietario' => 'Gobierno',
                'modelo' => 528,
                'precio' => 0,
                'x' => 1545.13,
                'y' => -1605.26,
                'z' => 13.4281,
                'a' => 269.528,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            110 => 
            array (
                'id' => 111,
                'propietario' => 'Gobierno',
                'modelo' => 497,
                'precio' => 0,
                'x' => -1679.61,
                'y' => 705.844,
                'z' => 30.779,
                'a' => 89.5481,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            111 => 
            array (
                'id' => 112,
                'propietario' => 'Gobierno',
                'modelo' => 411,
                'precio' => 20,
                'x' => -1959.73,
                'y' => 269.813,
                'z' => 35.2072,
                'a' => 42.6121,
                'color1' => '64',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 1,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            112 => 
            array (
                'id' => 113,
                'propietario' => 'Gobierno',
                'modelo' => 415,
                'precio' => 15,
                'x' => 1471.98,
                'y' => -1773.74,
                'z' => 13.6562,
                'a' => 322.616,
                'color1' => '40',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 1,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            113 => 
            array (
                'id' => 114,
                'propietario' => 'Gobierno',
                'modelo' => 451,
                'precio' => 15,
                'x' => 1458.65,
                'y' => -1774.39,
                'z' => 13.5936,
                'a' => 13.7521,
                'color1' => '125',
                'color2' => '125',
                'comprable' => '1',
                'moneda' => 1,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            114 => 
            array (
                'id' => 115,
                'propietario' => 'Gobierno',
                'modelo' => 604,
                'precio' => 3000,
                'x' => 1670.37,
                'y' => -1886.22,
                'z' => 13.2884,
                'a' => 57.7363,
                'color1' => '18',
                'color2' => '25',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            115 => 
            array (
                'id' => 116,
                'propietario' => 'Gobierno',
                'modelo' => 542,
                'precio' => 4000,
                'x' => 1631.92,
                'y' => -1900.45,
                'z' => 13.2968,
                'a' => 270.792,
                'color1' => '123',
                'color2' => '49',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            116 => 
            array (
                'id' => 117,
                'propietario' => 'Gobierno',
                'modelo' => 404,
                'precio' => 5000,
                'x' => 1668.06,
                'y' => -1899.14,
                'z' => 13.2818,
                'a' => 41.4088,
                'color1' => '115',
                'color2' => '117',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            117 => 
            array (
                'id' => 118,
                'propietario' => 'Gobierno',
                'modelo' => 561,
                'precio' => 70000,
                'x' => 1501.68,
                'y' => -1772.28,
                'z' => 13.9387,
                'a' => 43.3255,
                'color1' => '8',
                'color2' => '17',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            118 => 
            array (
                'id' => 119,
                'propietario' => 'Gobierno',
                'modelo' => 479,
                'precio' => 3300,
                'x' => 1669.17,
                'y' => -1892.31,
                'z' => 13.342,
                'a' => 51.0409,
                'color1' => '101',
                'color2' => '78',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            119 => 
            array (
                'id' => 120,
                'propietario' => 'Gobierno',
                'modelo' => 500,
                'precio' => 45000,
                'x' => 1503.09,
                'y' => -1747.13,
                'z' => 13.6621,
                'a' => 359.295,
                'color1' => '3',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            120 => 
            array (
                'id' => 121,
                'propietario' => 'Gobierno',
                'modelo' => 589,
                'precio' => 42000,
                'x' => 1426.44,
                'y' => -1802.21,
                'z' => 13.5956,
                'a' => 224.17,
                'color1' => '31',
                'color2' => '31',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            121 => 
            array (
                'id' => 122,
                'propietario' => 'Gobierno',
                'modelo' => 602,
                'precio' => 38000,
                'x' => 1501.29,
                'y' => -1774.12,
                'z' => 19.3229,
                'a' => 75.3057,
                'color1' => '70',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            122 => 
            array (
                'id' => 123,
                'propietario' => 'Gobierno',
                'modelo' => 603,
                'precio' => 45000,
                'x' => 1456.81,
                'y' => -1794.69,
                'z' => 13.7812,
                'a' => 220.783,
                'color1' => '58',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            123 => 
            array (
                'id' => 124,
                'propietario' => 'Gobierno',
                'modelo' => 506,
                'precio' => 185000,
                'x' => 1457.95,
                'y' => -1779.3,
                'z' => 19.1696,
                'a' => 1.76125,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            124 => 
            array (
                'id' => 125,
                'propietario' => 'Gobierno',
                'modelo' => 565,
                'precio' => 60000,
                'x' => 1425.27,
                'y' => -1808.91,
                'z' => 13.5666,
                'a' => 240.479,
                'color1' => '42',
                'color2' => '42',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            125 => 
            array (
                'id' => 126,
                'propietario' => 'Gobierno',
                'modelo' => 445,
                'precio' => 7000,
                'x' => 1631.71,
                'y' => -1909.92,
                'z' => 13.426,
                'a' => 272.908,
                'color1' => '66',
                'color2' => '97',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            126 => 
            array (
                'id' => 127,
                'propietario' => 'Gobierno',
                'modelo' => 478,
                'precio' => 8000,
                'x' => -1992.02,
                'y' => 250.674,
                'z' => 35.1672,
                'a' => 83.9691,
                'color1' => '66',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            127 => 
            array (
                'id' => 128,
                'propietario' => 'Gobierno',
                'modelo' => 489,
                'precio' => 70000,
                'x' => -1991.0,
                'y' => 256.413,
                'z' => 35.3156,
                'a' => 85.6616,
                'color1' => '112',
                'color2' => '120',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            128 => 
            array (
                'id' => 129,
                'propietario' => 'Gobierno',
                'modelo' => 579,
                'precio' => 75000,
                'x' => 1483.47,
                'y' => -1746.47,
                'z' => 13.4818,
                'a' => 359.088,
                'color1' => '53',
                'color2' => '53',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            129 => 
            array (
                'id' => 130,
                'propietario' => 'Gobierno',
                'modelo' => 560,
                'precio' => 75000,
                'x' => 523.629,
                'y' => -1290.79,
                'z' => 16.9475,
                'a' => 1.31224,
                'color1' => '125',
                'color2' => '125',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            130 => 
            array (
                'id' => 131,
                'propietario' => 'Gobierno',
                'modelo' => 551,
                'precio' => 10000,
                'x' => 519.455,
                'y' => -1290.61,
                'z' => 17.0424,
                'a' => 358.732,
                'color1' => '120',
                'color2' => '120',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            131 => 
            array (
                'id' => 132,
                'propietario' => 'Gobierno',
                'modelo' => 587,
                'precio' => 80000,
                'x' => 527.897,
                'y' => -1290.87,
                'z' => 16.97,
                'a' => 359.291,
                'color1' => '3',
                'color2' => '3',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            132 => 
            array (
                'id' => 133,
                'propietario' => 'Gobierno',
                'modelo' => 566,
                'precio' => 25000,
                'x' => 532.166,
                'y' => -1290.74,
                'z' => 17.0228,
                'a' => 0.0,
                'color1' => '60',
                'color2' => '60',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            133 => 
            array (
                'id' => 134,
                'propietario' => 'Gobierno',
                'modelo' => 533,
                'precio' => 20000,
                'x' => 538.966,
                'y' => -1290.96,
                'z' => 16.9513,
                'a' => 2.1154,
                'color1' => '62',
                'color2' => '62',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            134 => 
            array (
                'id' => 135,
                'propietario' => 'Gobierno',
                'modelo' => 496,
                'precio' => 22500,
                'x' => 548.238,
                'y' => -1291.49,
                'z' => 16.9644,
                'a' => 4.19405,
                'color1' => '25',
                'color2' => '25',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            135 => 
            array (
                'id' => 136,
                'propietario' => 'Gobierno',
                'modelo' => 412,
                'precio' => 19000,
                'x' => 555.341,
                'y' => -1290.13,
                'z' => 17.0833,
                'a' => 0.074019,
                'color1' => '6',
                'color2' => '6',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            136 => 
            array (
                'id' => 137,
                'propietario' => 'Gobierno',
                'modelo' => 463,
                'precio' => 55000,
                'x' => 2137.76,
                'y' => -1139.8,
                'z' => 24.9366,
                'a' => 119.298,
                'color1' => '125',
                'color2' => '125',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            137 => 
            array (
                'id' => 138,
                'propietario' => 'Gobierno',
                'modelo' => 475,
                'precio' => 42000,
                'x' => 2135.88,
                'y' => -1125.79,
                'z' => 25.2924,
                'a' => 83.1302,
                'color1' => '30',
                'color2' => '96',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            138 => 
            array (
                'id' => 139,
                'propietario' => 'Gobierno',
                'modelo' => 545,
                'precio' => 33000,
                'x' => 2136.5,
                'y' => -1131.19,
                'z' => 25.4853,
                'a' => 108.837,
                'color1' => '66',
                'color2' => '66',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            139 => 
            array (
                'id' => 140,
                'propietario' => 'Gobierno',
                'modelo' => 491,
                'precio' => 32000,
                'x' => 2135.85,
                'y' => -1135.86,
                'z' => 25.4412,
                'a' => 106.868,
                'color1' => '25',
                'color2' => '25',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            140 => 
            array (
                'id' => 141,
                'propietario' => 'Gobierno',
                'modelo' => 567,
                'precio' => 70000,
                'x' => 2119.63,
                'y' => -1124.74,
                'z' => 25.2432,
                'a' => 303.711,
                'color1' => '93',
                'color2' => '64',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            141 => 
            array (
                'id' => 142,
                'propietario' => 'Gobierno',
                'modelo' => 534,
                'precio' => 60000,
                'x' => 2119.74,
                'y' => -1131.79,
                'z' => 25.0424,
                'a' => 302.697,
                'color1' => '37',
                'color2' => '37',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            142 => 
            array (
                'id' => 143,
                'propietario' => 'Gobierno',
                'modelo' => 535,
                'precio' => 35000,
                'x' => 2119.04,
                'y' => -1139.21,
                'z' => 24.7991,
                'a' => 306.113,
                'color1' => '3',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            143 => 
            array (
                'id' => 144,
                'propietario' => 'Gobierno',
                'modelo' => 554,
                'precio' => 42000,
                'x' => 1477.53,
                'y' => -1746.75,
                'z' => 13.6335,
                'a' => 1.2896,
                'color1' => '15',
                'color2' => '32',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            144 => 
            array (
                'id' => 145,
                'propietario' => 'Gobierno',
                'modelo' => 400,
                'precio' => 70000,
                'x' => 1472.29,
                'y' => -1746.28,
                'z' => 13.6392,
                'a' => 359.982,
                'color1' => '123',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            145 => 
            array (
                'id' => 146,
                'propietario' => 'Gobierno',
                'modelo' => 414,
                'precio' => 90000,
                'x' => 1460.06,
                'y' => -1746.98,
                'z' => 13.6406,
                'a' => 359.183,
                'color1' => '28',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            146 => 
            array (
                'id' => 147,
                'propietario' => 'Gobierno',
                'modelo' => 482,
                'precio' => 120000,
                'x' => 1508.46,
                'y' => -1747.09,
                'z' => 13.6681,
                'a' => 359.023,
                'color1' => '37',
                'color2' => '37',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            147 => 
            array (
                'id' => 148,
                'propietario' => 'Gobierno',
                'modelo' => 480,
                'precio' => 225000,
                'x' => -1957.33,
                'y' => 303.683,
                'z' => 35.2432,
                'a' => 133.499,
                'color1' => '12',
                'color2' => '12',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            148 => 
            array (
                'id' => 149,
                'propietario' => 'Gobierno',
                'modelo' => 578,
                'precio' => 230000,
                'x' => -1990.71,
                'y' => 243.865,
                'z' => 35.7954,
                'a' => 84.9635,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            149 => 
            array (
                'id' => 150,
                'propietario' => 'Gobierno',
                'modelo' => 477,
                'precio' => 250000,
                'x' => -1960.17,
                'y' => 257.467,
                'z' => 35.2273,
                'a' => 43.2015,
                'color1' => '121',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            150 => 
            array (
                'id' => 151,
                'propietario' => 'Gobierno',
                'modelo' => 409,
                'precio' => 1000000,
                'x' => 1467.11,
                'y' => -1747.87,
                'z' => 13.3492,
                'a' => 0.3858,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            151 => 
            array (
                'id' => 152,
                'propietario' => 'Gobierno',
                'modelo' => 408,
                'precio' => 0,
                'x' => -126.498,
                'y' => -1501.46,
                'z' => 4.21421,
                'a' => 136.448,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 6,
            ),
            152 => 
            array (
                'id' => 153,
                'propietario' => 'Gobierno',
                'modelo' => 408,
                'precio' => 0,
                'x' => -120.156,
                'y' => -1508.04,
                'z' => 4.13295,
                'a' => 136.905,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 6,
            ),
            153 => 
            array (
                'id' => 154,
                'propietario' => 'Gobierno',
                'modelo' => 408,
                'precio' => 0,
                'x' => -111.604,
                'y' => -1587.82,
                'z' => 3.18897,
                'a' => 122.793,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 6,
            ),
            154 => 
            array (
                'id' => 155,
                'propietario' => 'Gobierno',
                'modelo' => 408,
                'precio' => 0,
                'x' => -109.125,
                'y' => -1592.32,
                'z' => 3.10105,
                'a' => 121.934,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 6,
            ),
            155 => 
            array (
                'id' => 156,
                'propietario' => 'Gobierno',
                'modelo' => 408,
                'precio' => 0,
                'x' => -105.97,
                'y' => -1597.38,
                'z' => 3.09272,
                'a' => 123.696,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 6,
            ),
            156 => 
            array (
                'id' => 157,
                'propietario' => 'Gobierno',
                'modelo' => 408,
                'precio' => 0,
                'x' => -102.576,
                'y' => -1601.98,
                'z' => 3.09469,
                'a' => 122.508,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 6,
            ),
            157 => 
            array (
                'id' => 158,
                'propietario' => 'Gobierno',
                'modelo' => 408,
                'precio' => 0,
                'x' => -114.73,
                'y' => -1613.18,
                'z' => 3.19812,
                'a' => 16.9179,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 6,
            ),
            158 => 
            array (
                'id' => 159,
                'propietario' => 'Gobierno',
                'modelo' => 408,
                'precio' => 0,
                'x' => -120.712,
                'y' => -1613.97,
                'z' => 3.84595,
                'a' => 13.2772,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 6,
            ),
            159 => 
            array (
                'id' => 160,
                'propietario' => 'Gobierno',
                'modelo' => 408,
                'precio' => 0,
                'x' => -186.688,
                'y' => -1555.44,
                'z' => 7.297,
                'a' => 229.635,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 6,
            ),
            160 => 
            array (
                'id' => 161,
                'propietario' => 'Gobierno',
                'modelo' => 408,
                'precio' => 0,
                'x' => -189.85,
                'y' => -1560.93,
                'z' => 7.2426,
                'a' => 227.564,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 6,
            ),
            161 => 
            array (
                'id' => 162,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2822.07,
                'y' => -2624.44,
                'z' => -0.0876,
                'a' => 89.6143,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            162 => 
            array (
                'id' => 163,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2821.58,
                'y' => -2618.06,
                'z' => -0.2381,
                'a' => 82.3052,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            163 => 
            array (
                'id' => 164,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2822.26,
                'y' => -2611.5,
                'z' => -0.7854,
                'a' => 91.6937,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            164 => 
            array (
                'id' => 165,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2821.52,
                'y' => -2604.74,
                'z' => -0.1236,
                'a' => 87.5986,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            165 => 
            array (
                'id' => 166,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2821.52,
                'y' => -2596.74,
                'z' => -0.3082,
                'a' => 90.4083,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            166 => 
            array (
                'id' => 167,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2822.91,
                'y' => -2584.06,
                'z' => -0.3235,
                'a' => 87.4044,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            167 => 
            array (
                'id' => 168,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2839.35,
                'y' => -2625.99,
                'z' => 0.2129,
                'a' => 272.277,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            168 => 
            array (
                'id' => 169,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2839.33,
                'y' => -2617.7,
                'z' => -0.6352,
                'a' => 273.978,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            169 => 
            array (
                'id' => 170,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2839.43,
                'y' => -2608.04,
                'z' => 0.1093,
                'a' => 265.808,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            170 => 
            array (
                'id' => 171,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2840.28,
                'y' => -2598.57,
                'z' => 0.1278,
                'a' => 270.083,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            171 => 
            array (
                'id' => 172,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2838.01,
                'y' => -2586.62,
                'z' => -0.7477,
                'a' => 273.957,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            172 => 
            array (
                'id' => 173,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2838.26,
                'y' => -2576.27,
                'z' => -0.7139,
                'a' => 274.884,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            173 => 
            array (
                'id' => 174,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2822.48,
                'y' => -2590.11,
                'z' => 0.068,
                'a' => 88.2848,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            174 => 
            array (
                'id' => 175,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2839.15,
                'y' => -2592.76,
                'z' => -0.0994,
                'a' => 264.828,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            175 => 
            array (
                'id' => 176,
                'propietario' => 'Gobierno',
                'modelo' => 453,
                'precio' => 0,
                'x' => 2801.81,
                'y' => -2583.29,
                'z' => -0.7696,
                'a' => 181.831,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 10,
            ),
            176 => 
            array (
                'id' => 177,
                'propietario' => 'Gobierno',
                'modelo' => 466,
                'precio' => 5000,
                'x' => 1659.95,
                'y' => -1901.61,
                'z' => 13.2939,
                'a' => 359.81,
                'color1' => '18',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            177 => 
            array (
                'id' => 178,
                'propietario' => 'Gobierno',
                'modelo' => 429,
                'precio' => 15,
                'x' => -1953.59,
                'y' => 298.972,
                'z' => 35.1484,
                'a' => 142.652,
                'color1' => '7',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 1,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            178 => 
            array (
                'id' => 179,
                'propietario' => 'Gobierno',
                'modelo' => 517,
                'precio' => 6500,
                'x' => 1632.2,
                'y' => -1904.55,
                'z' => 13.4067,
                'a' => 269.611,
                'color1' => '1',
                'color2' => '3',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            179 => 
            array (
                'id' => 180,
                'propietario' => 'Gobierno',
                'modelo' => 536,
                'precio' => 40000,
                'x' => 2119.9,
                'y' => -1144.58,
                'z' => 24.3798,
                'a' => 299.297,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            180 => 
            array (
                'id' => 181,
                'propietario' => 'Gobierno',
                'modelo' => 580,
                'precio' => 32000,
                'x' => 2136.3,
                'y' => -1144.72,
                'z' => 24.637,
                'a' => 95.8218,
                'color1' => '6',
                'color2' => '6',
                'comprable' => '1',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            181 => 
            array (
                'id' => 182,
                'propietario' => 'Gobierno',
                'modelo' => 598,
                'precio' => 0,
                'x' => 283.61,
                'y' => 1429.48,
                'z' => 10.3312,
                'a' => 88.203,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            182 => 
            array (
                'id' => 183,
                'propietario' => 'Gobierno',
                'modelo' => 598,
                'precio' => 0,
                'x' => 283.509,
                'y' => 1433.61,
                'z' => 10.3331,
                'a' => 89.0617,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            183 => 
            array (
                'id' => 184,
                'propietario' => 'Gobierno',
                'modelo' => 598,
                'precio' => 0,
                'x' => 283.678,
                'y' => 1437.77,
                'z' => 10.3325,
                'a' => 89.1797,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            184 => 
            array (
                'id' => 185,
                'propietario' => 'Gobierno',
                'modelo' => 497,
                'precio' => 0,
                'x' => 256.253,
                'y' => 1472.07,
                'z' => 12.8248,
                'a' => 90.0708,
                'color1' => '0',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            185 => 
            array (
                'id' => 186,
                'propietario' => 'Gobierno',
                'modelo' => 532,
                'precio' => 0,
                'x' => -31.229,
                'y' => 61.6207,
                'z' => 4.116,
                'a' => 67.7852,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            186 => 
            array (
                'id' => 187,
                'propietario' => 'Gobierno',
                'modelo' => 532,
                'precio' => 0,
                'x' => -25.6985,
                'y' => 75.0524,
                'z' => 4.0985,
                'a' => 73.7121,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            187 => 
            array (
                'id' => 188,
                'propietario' => 'Gobierno',
                'modelo' => 532,
                'precio' => 0,
                'x' => -21.0595,
                'y' => 88.5285,
                'z' => 4.1118,
                'a' => 66.7985,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            188 => 
            array (
                'id' => 189,
                'propietario' => 'Gobierno',
                'modelo' => 532,
                'precio' => 0,
                'x' => -54.3132,
                'y' => 92.1332,
                'z' => 4.1124,
                'a' => 249.363,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
            189 => 
            array (
                'id' => 190,
                'propietario' => 'Gobierno',
                'modelo' => 532,
                'precio' => 0,
                'x' => -57.875,
                'y' => 80.2766,
                'z' => 4.0246,
                'a' => 251.74,
                'color1' => '1',
                'color2' => '1',
                'comprable' => '0',
                'moneda' => 0,
                'faccion' => 0,
                'trabajo' => 0,
            ),
        ));
        
        
    }
}