<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('usuarios', function (Blueprint $table) {
            $table->increments('ID');
            $table->string('Username');
            $table->string('Email')->unique();
            $table->string('Password');
            $table->float('posX', 10, 0);
            $table->float('posY', 10, 0);
            $table->float('posZ', 10, 0);
            $table->integer('Admin')->default(0);
            $table->string('Sexo', 1);
            $table->integer('Edad')->default(0);
            $table->string('Skin', 3);
            $table->float('Vida', 10, 0);
            $table->float('Chaleco', 10, 0);
            $table->string('Registro', 15)->default('19/7/2014');
            $table->integer('Tutorial')->default(0);
            $table->integer('Money');
            $table->integer('Banco')->default(0);
            $table->integer('Moneda')->default(0);
            $table->string('Cargos', 1)->default('0');
            $table->string('Duty', 1)->default('0');
            $table->string('SkinTrabajo', 3)->default('280');
            $table->string('Nivel', 2)->default('1');
            $table->string('Experiencia', 3)->default('0');
            $table->string('Agonizando', 1)->default('0');
            $table->string('GPS', 1)->default('0');
            $table->string('Radio', 1)->default('0');
            $table->string('Numero', 10)->default('0');
            $table->integer('Interior')->default(0);
            $table->integer('MundoVirtual')->default(0);
            $table->integer('Materiales')->default(0);
            $table->integer('Sed')->default(0);
            $table->integer('Trabajo')->default(0);
            $table->integer('Trabajo2')->default(0);
            $table->string('Faccion', 5)->default('0');
            $table->string('Rango', 10)->nullable();
            $table->integer('Crack')->default(0);
            $table->integer('Medicamentos')->default(0);
            $table->string('Agenda', 2)->default('0');
            $table->string('Licencia', 5)->default('0');
            $table->integer('TiempoPD')->default(0);
            $table->integer('TiempoJail')->default(0);
            $table->integer('TiempoCarcelM')->default(0);
            $table->integer('Repuestos')->default(0);
            $table->float('hx', 10, 0);
            $table->float('hy', 10, 0);
            $table->float('hz', 10, 0);
            $table->string('Baneado', 2)->default('0');
            $table->string('razon', 32)->default('Ninguno');
            $table->string('IP', 15);
            $table->integer('NMute')->default(0);
            $table->integer('changenamefree')->default(0);
            $table->integer('Online')->default(0);
            $table->integer('EMS')->default(0);
            $table->integer('TiempoCarcelS')->default(0);
            $table->integer('Changed')->default(0);
            $table->integer('Multas')->default(0);
            $table->integer('Stats')->default(0);
            $table->string('EnCasa', 10)->default('0');
            $table->string('EnRopero', 10)->default('0');
            $table->integer('EnGarage')->default(0);
            $table->integer('VIP')->default(0);
            $table->integer('FinDia')->default(0);
            $table->integer('FinMes')->default(0);
            $table->integer('FinAno')->default(0);
            $table->integer('hprecio')->default(0);
            $table->integer('h2precio')->default(0);
            $table->integer('hmoneda')->default(0);
            $table->integer('h2moneda')->default(0);
            $table->integer('CasaID')->default(0);
            $table->integer('CasaID2')->default(0);
            $table->string('WP0', 2)->default('0');
            $table->string('WP1', 2)->default('0');
            $table->string('WP2', 2)->default('0');
            $table->string('WP3', 2)->default('0');
            $table->string('WP4', 2)->default('0');
            $table->string('WP5', 2)->default('0');
            $table->string('WP6', 2)->default('0');
            $table->string('WP7', 2)->default('0');
            $table->string('WP8', 2)->default('0');
            $table->string('WP9', 2)->default('0');
            $table->string('WP10', 2)->default('0');
            $table->string('WP11', 2)->default('0');
            $table->string('WP12', 2)->default('0');
            $table->string('NivelArmero', 3)->default('1');
            $table->string('ExpArmero', 3)->default('0');
            $table->integer('NivelPescador')->default(1);
            $table->integer('ExpPescador')->default(0);
            $table->integer('NivelPiloto')->default(1);
            $table->integer('ExpPiloto')->default(0);
            $table->string('NivelCamionero', 3)->default('1');
            $table->string('ExpCamionero', 3)->default('0');
            $table->integer('NivelTransportista')->default(1);
            $table->integer('ExpTransportista')->default(0);
            $table->integer('NivelBasurero')->default(1);
            $table->integer('ExpBasurero')->default(0);
            $table->integer('NivelLadron')->default(1);
            $table->integer('ExpLadron')->default(0);
            $table->float('OX', 10, 0)->default(0);
            $table->float('OY', 10, 0)->default(0);
            $table->float('OZ', 10, 0)->default(0);
            $table->float('OA', 10, 0)->default(0);
            $table->integer('VE1');
            $table->integer('VE2');
            $table->integer('VE3');
            $table->integer('VE4');
            $table->integer('vMoneda')->default(0);
            $table->string('Modelo', 3);
            $table->integer('vTraba')->default(0);
            $table->integer('vGas')->default(0);
            $table->integer('vinterior')->default(0);
            $table->integer('vvw')->default(0);
            $table->integer('Color1');
            $table->integer('Color2');
            $table->float('VidaV', 10, 0)->default(1000);
            $table->integer('vBaul')->default(0);
            $table->integer('vBaul2')->default(0);
            $table->integer('vBaul3')->default(0);
            $table->integer('vBaul4')->default(0);
            $table->integer('vBaul5')->default(0);
            $table->integer('vBaul6')->default(0);
            $table->integer('vBaul7')->default(0);
            $table->integer('vBaul8')->default(0);
            $table->integer('PaintJob')->default(-1);
            $table->string('1Patente', 32)->default('0');
            $table->integer('1Componentes0')->default(0);
            $table->integer('1Componentes1')->default(0);
            $table->integer('1Componentes2')->default(0);
            $table->integer('1Componentes3')->default(0);
            $table->integer('1Componentes4')->default(0);
            $table->integer('1Componentes5')->default(0);
            $table->integer('1Componentes6')->default(0);
            $table->integer('1Componentes7')->default(0);
            $table->integer('1Componentes8')->default(0);
            $table->integer('1Componentes9')->default(0);
            $table->integer('1Componentes10')->default(0);
            $table->integer('1Componentes11')->default(0);
            $table->integer('1Componentes12')->default(0);
            $table->integer('1Componentes13')->default(0);
            $table->string('Precio', 50)->default('0');
            $table->float('X', 10, 0);
            $table->float('Y', 10, 0);
            $table->float('Z', 10, 0);
            $table->float('A', 10, 0);
            $table->integer('Ovw')->default(0);
            $table->string('Segurov', 2)->default('0');
            $table->integer('Ointerior')->default(0);
            $table->float('OX2', 10, 0)->default(0);
            $table->float('OY2', 10, 0)->default(0);
            $table->float('OZ2', 10, 0)->default(0);
            $table->float('OA2', 10, 0)->default(0);
            $table->integer('V2E1');
            $table->integer('V2E2');
            $table->integer('V2E3');
            $table->integer('V2E4');
            $table->integer('v2Moneda')->default(0);
            $table->integer('Modelo2')->default(0);
            $table->integer('v2Traba')->default(0);
            $table->integer('v2Gas')->default(0);
            $table->integer('v2interior')->default(0);
            $table->integer('v2vw')->default(0);
            $table->integer('2Color1')->default(0);
            $table->integer('2Color2')->default(0);
            $table->float('VidaV2', 10, 0)->default(0);
            $table->integer('v2Baul')->default(0);
            $table->integer('v2Baul2')->default(0);
            $table->integer('v2Baul3')->default(0);
            $table->integer('v2Baul4')->default(0);
            $table->integer('v2Baul5')->default(0);
            $table->integer('v2Baul6')->default(0);
            $table->integer('v2Baul7')->default(0);
            $table->integer('v2Baul8')->default(0);
            $table->integer('PaintJob2')->default(-1);
            $table->string('2Patente', 32)->default('0');
            $table->integer('2Componentes0')->default(0);
            $table->integer('2Componentes1')->default(0);
            $table->integer('2Componentes2')->default(0);
            $table->integer('2Componentes3')->default(0);
            $table->integer('2Componentes4')->default(0);
            $table->integer('2Componentes5')->default(0);
            $table->integer('2Componentes6')->default(0);
            $table->integer('2Componentes7')->default(0);
            $table->integer('2Componentes8')->default(0);
            $table->integer('2Componentes9')->default(0);
            $table->integer('2Componentes10')->default(0);
            $table->integer('2Componentes11')->default(0);
            $table->integer('2Componentes12')->default(0);
            $table->integer('2Componentes13')->default(0);
            $table->integer('Precio2')->default(0);
            $table->float('X2', 10, 0)->default(0);
            $table->float('Y2', 10, 0)->default(0);
            $table->float('Z2', 10, 0)->default(0);
            $table->float('A2', 10, 0)->default(0);
            $table->integer('Ovw2')->default(0);
            $table->integer('Segurov2')->default(0);
            $table->integer('Ointerior2')->default(0);
            $table->integer('RopaBasu')->default(0);
            $table->integer('RopaMedi')->default(0);
            $table->integer('RopaMeca')->nullable()->default(0);
            $table->integer('RopaMine')->default(0);
            $table->integer('Martillo')->default(0);
            $table->integer('Destornillador')->default(0);
            $table->integer('Barreta')->default(0);
            $table->integer('Balde')->default(0);
            $table->integer('ent_totem')->default(0);
            $table->string('totem', 32)->nullable();
            $table->integer('totems')->default(0);
            $table->float('OX3', 10, 0)->default(0);
            $table->float('OY3', 10, 0)->default(0);
            $table->float('OZ3', 10, 0)->default(0);
            $table->float('OA3', 10, 0)->default(0);
            $table->integer('V3E1');
            $table->integer('V3E2');
            $table->integer('V3E3');
            $table->integer('V3E4');
            $table->integer('v3Moneda')->default(0);
            $table->integer('Modelo3')->default(0);
            $table->integer('v3Traba')->default(0);
            $table->integer('v3Gas')->default(0);
            $table->integer('v3interior')->default(0);
            $table->integer('v3vw')->default(0);
            $table->integer('3Color1')->default(0);
            $table->integer('3Color2')->default(0);
            $table->float('VidaV3', 10, 0)->default(0);
            $table->integer('v3Baul')->default(0);
            $table->integer('v3Baul2')->default(0);
            $table->integer('v3Baul3')->default(0);
            $table->integer('v3Baul4')->default(0);
            $table->integer('v3Baul5')->default(0);
            $table->integer('v3Baul6')->default(0);
            $table->integer('v3Baul7')->default(0);
            $table->integer('v3Baul8')->default(0);
            $table->integer('PaintJob3')->default(-1);
            $table->string('3Patente', 32)->default('0');
            $table->integer('3Componentes0')->default(0);
            $table->integer('3Componentes1')->default(0);
            $table->integer('3Componentes2')->default(0);
            $table->integer('3Componentes3')->default(0);
            $table->integer('3Componentes4')->default(0);
            $table->integer('3Componentes5')->default(0);
            $table->integer('3Componentes6')->default(0);
            $table->integer('3Componentes7')->default(0);
            $table->integer('3Componentes8')->default(0);
            $table->integer('3Componentes9')->default(0);
            $table->integer('3Componentes10')->default(0);
            $table->integer('3Componentes11')->default(0);
            $table->integer('3Componentes12')->default(0);
            $table->integer('3Componentes13')->default(0);
            $table->integer('Precio3')->default(0);
            $table->float('X3', 10, 0)->default(0);
            $table->float('Y3', 10, 0)->default(0);
            $table->float('Z3', 10, 0)->default(0);
            $table->float('A3', 10, 0)->default(0);
            $table->integer('Ovw3')->default(0);
            $table->integer('Segurov3')->default(0);
            $table->integer('Ointerior3')->default(0);
            $table->float('OX4', 10, 0)->default(0);
            $table->float('OY4', 10, 0)->default(0);
            $table->float('OZ4', 10, 0)->default(0);
            $table->float('OA4', 10, 0)->default(0);
            $table->integer('V4E1');
            $table->integer('V4E2');
            $table->integer('V4E3');
            $table->integer('V4E4');
            $table->integer('v4Moneda')->default(0);
            $table->integer('Modelo4')->default(0);
            $table->integer('v4Traba')->default(0);
            $table->integer('v4Gas')->default(0);
            $table->integer('v4interior')->default(0);
            $table->integer('v4vw')->default(0);
            $table->integer('4Color1')->default(0);
            $table->integer('4Color2')->default(0);
            $table->float('VidaV4', 10, 0)->default(0);
            $table->integer('v4Baul')->default(0);
            $table->integer('v4Baul2')->default(0);
            $table->integer('v4Baul3')->default(0);
            $table->integer('v4Baul4')->default(0);
            $table->integer('v4Baul5')->default(0);
            $table->integer('v4Baul6')->default(0);
            $table->integer('v4Baul7')->default(0);
            $table->integer('v4Baul8')->default(0);
            $table->integer('PaintJob4')->default(-1);
            $table->string('4Patente', 32)->default('0');
            $table->integer('4Componentes0')->default(0);
            $table->integer('4Componentes1')->default(0);
            $table->integer('4Componentes2')->default(0);
            $table->integer('4Componentes3')->default(0);
            $table->integer('4Componentes4')->default(0);
            $table->integer('4Componentes5')->default(0);
            $table->integer('4Componentes6')->default(0);
            $table->integer('4Componentes7')->default(0);
            $table->integer('4Componentes8')->default(0);
            $table->integer('4Componentes9')->default(0);
            $table->integer('4Componentes10')->default(0);
            $table->integer('4Componentes11')->default(0);
            $table->integer('4Componentes12')->default(0);
            $table->integer('4Componentes13')->default(0);
            $table->integer('Precio4')->default(0);
            $table->float('X4', 10, 0)->default(0);
            $table->float('Y4', 10, 0)->default(0);
            $table->float('Z4', 10, 0)->default(0);
            $table->float('A4', 10, 0)->default(0);
            $table->integer('Ovw4')->default(0);
            $table->integer('Segurov4')->default(0);
            $table->integer('Ointerior4')->default(0);
            $table->integer('NivelMinero')->default(1);
            $table->integer('ExpMinero')->default(0);
            $table->integer('Regalo')->default(0);
            $table->integer('arrestado')->default(0);
            $table->integer('horasjugadas')->default(0);
            $table->string('TipoCarcel', 3)->default('0');
            $table->string('SocioHP', 3)->default('0');
            $table->integer('Hambre');
            $table->integer('Patines');
            $table->integer('PuntosCarrera')->default(0);
            $table->integer('TieneEmisora')->default(0);
            $table->string('NombreEmisora', 90);
            $table->string('Conexion', 90)->default('1');
            $table->integer('Semillas')->default(0);
            $table->integer('Swat')->default(0);
            $table->rememberToken();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
